version: "3.8"

services:
  core:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./api/src:/app/src
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
